language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.5/x86_64/bin/
  global:
    secure: X2mbfFMOql9DE5orv5mg/GFPAwTzDb4SBqyLe5g1TaR4EdB06q43mvxqQyEWu3VW97EOvpunthGcBdzn8Zi0EVchjktgWVeS3yOetnC92JF9RgU51lRe/v58CsZhpaE3rMfNu0cvBu3iIwuDrj77HZSYqb3YBuwuVvkle6qjQeE=
install:
- export main_repo_branch=$TRAVIS_BRANCH
- if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" ]]; then main_repo_branch=development ; fi

# Install NEURON
- wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.5/nrn-7.5.tar.gz
- tar xzvf nrn-7.5.tar.gz
- cd nrn-7.5
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make
- make install
- cd src/nrnpython
- sudo python setup.py install
- cd ../../..

# Install NetPyNE, libNeuroML, pyNeuroML & required libraries
- sudo pip install netpyne
- sudo pip install numpy
- sudo pip install scipy
- sudo pip install lxml
- sudo pip install libneuroml
- sudo pip install pyneuroml
- sudo apt-get install python-tk
- sudo pip install matplotlib

# Install jNeuroML
- svn checkout svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar
- export JNML_HOME=$PWD/jNeuroMLJar

# Install org.geppetto.model
- git clone https://github.com/openworm/org.geppetto.model.git -b $main_repo_branch
- cd org.geppetto.model
- mvn install
- cd ..

# Todo: remove for development
- if [ $TRAVIS_BRANCH == "pg_netpyne" ]; then main_repo_branch="pg_netpyne" ; fi
- echo "Cloning branch " $main_repo_branch

# Install org.geppetto.core
- git clone https://github.com/openworm/org.geppetto.core.git -b $main_repo_branch
- cd org.geppetto.core
- mvn install
- cd ..
