language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.4/x86_64/bin/
  global:
    secure: X2mbfFMOql9DE5orv5mg/GFPAwTzDb4SBqyLe5g1TaR4EdB06q43mvxqQyEWu3VW97EOvpunthGcBdzn8Zi0EVchjktgWVeS3yOetnC92JF9RgU51lRe/v58CsZhpaE3rMfNu0cvBu3iIwuDrj77HZSYqb3YBuwuVvkle6qjQeE=
install:
- export model_repo_branch=$TRAVIS_BRANCH
- if [[ ${model_repo_branch} != "master" && ${model_repo_branch} != "development" ]]; then model_repo_branch=development ; fi
- export core_repo_branch=$TRAVIS_BRANCH
- if [[ ${core_repo_branch} != "master" && ${core_repo_branch} != "development" ]]; then core_repo_branch=livemix ; fi


# Install org.geppetto.model
- echo "Using branch for org.geppetto.model $model_repo_branch"
- git clone https://github.com/openworm/org.geppetto.model.git -b $model_repo_branch
- cd org.geppetto.model
- git status
- mvn install
- cd ..

- echo "Using branch for org.geppetto.core $model_repo_branch"
- git clone https://github.com/openworm/org.geppetto.core.git -b $core_repo_branch
- cd org.geppetto.core
- git status
- mvn install
- cd ..

# Install NEURON
- wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/nrn-7.4.tar.gz
- tar xzvf nrn-7.4.tar.gz
- cd nrn-7.4
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make
- make install
- cd src/nrnpython
- sudo python setup.py install
- cd ../../..

# Install NetPyNE, libNeuroML, pyNeuroML & required libraries
- sudo pip install numpy
- sudo pip install scipy
- sudo pip install lxml
- sudo pip install libneuroml
- sudo pip install pyneuroml
- sudo apt-get install python-tk
- sudo pip install matplotlib
- sudo pip install netpyne

# Install jNeuroML
- svn checkout svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar
- export JNML_HOME=$PWD/jNeuroMLJar

